sudo: required
services:
  - docker

before_install:
  - docker build -t isurug/docker-react -f Dockerfile.dev .

# script:
  # - docker run isurug/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true isurug/docker-react npm run test